language: go
sudo: required
go:
  - 1.5.2

env:
    matrix:
       - GIMME_OS=windows GIMME_ARCH=amd64
       - GIMME_OS=linux GIMME_ARCH=amd64
       - GIMME_OS=linux GIMME_ARCH=386
       - GIMME_OS=darwin GIMME_ARCH=amd64
    global:
       - secure: c/hl3zSgofRYSgIAgpStLEDx8szp1s1P9Gh3+fKNL9B/134j5B48arOx/bzWquUSKnvfwYddK4mlMDNDJBt0E2nul0nILTO1DTG7MTVExXKapVtdCj/9+P4OWLJTi8rDbC8d3N+t6E/mpczwnFVA3CPraDrEXWFmmRtm62eZLbMAvpESVdWF4xu8+9cDdv507H1re0d+IPFH9PK+B7aokyAjFVzf2719TYV7o9v3NakkLIWlnR18PnB6RX7vHBV7ziGWBOWHhpJIpne8StlBNTPwlbiGb80lNdUT2BLr9o66VuOT11L3K4QromWroDwiWc6MCA0Lvs6r8+I3PHebvXVjVEuzeSwJF9Szhe+UDL2FhFAdjecJ94tmfOG6X/P83Gl3aH3JnRHNgF7SnyO+WCB214w2zWz7EFCRJ9ji2SiqbmUFrbhxkGKF1RkYQP/r7NSq7QR20Esyp9vZurwLD7Qm7WnhkS0MFfBNKAFX/mPdsoajrqNzfUDR6/VYsiCQNreuTOawQamxYQ+IjcvG+3UIiEXPWuifd8idB2lprUwBlwHy0joUDNUwu6+Jb7xcUCbqK9w/ZYShUfpfSUKn5LMquGJpsTSeDXqfBJWQqR5e1QToteFu8UwyRuLUg2qvUwVS81T3NPy0Bg+L2v+TnInOnDWc8oIg2xJM5WaZATU=
       - secure: agExFpqoamoCHJY/vC66FwGJA2B6HXkW5cdgX2+CraeO4g1SVRJiX3296l/msFYbCfnTn7GuBnkpyhrbZ6NzndHGgXCjD0Q5RG85QF2ylVVr7/rlf/GC1l+IgxR7XmbXBv0DgfzFkrTbKqDJUJ6e5jpj29RKRHKEuX0f+OvycNL4b/tJIM4fyUcPq5SUTfYjAFwxh/00zkNhLjw3o24N3kK/JU8hipFbyGOf0pGAQg6rpZ3oDgHD24AoLRXCLFrjs+V07AXxMRqN+sCxYRxiQs8hYdCRgTVjyCTiAqDiV5Xu6lUtLzbVHWORnOP9+8GDnrI85Gv1lPpfn6nQNF+fxmcYBWq/RhebR7Mgc8v94yWQacBOuyxpgNY/FPO2XXXTL5y3PRxndsPoe8L7k3b9b2kx4H4/elkIRM/KMk1DdM7E1x4q3EhQUTKA7E6ZzWficuYL8OLHbLcKeASK+WDoJgWbXTzbVx4GgiKpp2gFQ19Kfs84t0lCU44OVg1OmksOS7llff47lgMJL5NPlIV77Dddmlud+9aPi0O4NUq8B8o2mpt8C13re0z8HNL5ce2fmHGi/XXnMMdSkTv6oC/jwqx4fo+6AxvVSxb6Dqh0U3gqmnlZngbz5UZCugp3GCSbNfvcMoyzWWx2AQTW6Y/Kpx+PWDLULV/19BTGez6L7m4=

after_script:
- ls -l ../../../../bin

# Workaround for travis-ci/gimme#25 to pick up latest version of gimme and run again
before_install:
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR
  - eval "$(./gimme 1.5)"
  - go version
  - go env

# Part of the same workaround.
before_script:
  - go get -d -v ./...

# Part of the same workaround.
script:
  - go build -v ./...
