# ~~~ How to use Appveyor ~~~
# Preconditions: JFrog Platform instance
#
# = Trigger tests on commits =
#   1. Create a new project in Appveyor and choose jfrog-cli-go.
#   2. In project settings, copy the 'Webhook URL' and create a new 'Push events' Webhook in Github.
#
# = Configure Artifactory =
#   1. Create all necessary repositories for tests according to the README.
#   2. Create a remote Nuget repository in Artifactory:
#     A. Repository Key: choco
#     B. Url: https://chocolatey.org
#     * The test uses Chocolatey package manager to download Gradle Nuget package through Artifactory's cache.
#
# = Override credentials in Appveyor in case of a fork =
#   1. In the project at Appveyor - Go to settings -> Environment.
#   2. Override 'JFROG_CLI_RT_URL' and 'JFROG_CLI_RT_USER'
#   3. Override 'JFROG_CLI_RT_PASSWORD' with variable encryption.

image:
  - Visual Studio 2019

build: off
skip_tags: true
stack: go 1.14, node 15, jdk 8
clone_folder: c:\gopath\src\github.com\jfrog\jfrog-cli
environment:
  GOPATH: c:\gopath
  # Added in order to prevent fetching the outdated dependencies versions from go cache.
  GOPROXY: direct
  GO111MODULE: on
  CGO_ENABLED: 0
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  # .NET CLI version
  CLI_VERSION: Latest

  JFROG_CLI_RT_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQm0ihToJ6/4LiR411QpvqDgYYE7Y4Eif2e+wYndvHXnW
  JFROG_CLI_RT_USER:
    secure: WpAIyjR9We+eTY9g3LHbyw==
  JFROG_CLI_RT_PASSWORD:
    secure: XFf7zLJIBm1/09Mqwlkylg==
  JFROG_CLI_DIST_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQrfLmtDrzDd5Qphea4gOE0Lu1Uz2Xa/y+D0Mld917gwy
  JFROG_CLI_ACCESS_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQph5j1FANSk/QUtRJvh8kSfFYyaZd4ONAf1aP/WV9BOA
  JFROG_CLI_ADMIN_TOKEN:
    secure: sStoT/GxZjEl/toWXau6wanS9NdCTsTxApUZCE7TTt4Wp4lVUwg1OqzdwWNic4R9YnAu90VY+5F/vI7I6Ijl1V/GcSCFLSVEr03rJj7OfzRkt5+obiNNotiBR9cP7bKQrCCAf2044fOukKPrjvZW7cV2tFoBQP8TmetaVmogBk52BMNcC44+MsLmh060htRFIP2WnZdiaQd0llF0xeqvMxKnomhZYi5D142t+14Bs6WeLqdaDcLBGZLT/EpfEu7y6xUXeSoMqI4nlYp/JcULIb0W9dTeZPrAFPA6mJXHIID1WnKBSL/mJszbqLRPRn2+uFxtDlikGzswVIuXiLtk2quczKJgOoH7PtUkv6ChRnErSEgfAq4r8F3mkjpvSmp0g1a5eyq+/8D8mOgopOjEZ4PwQtzw4Rfg1Enk0ra//adpYckQFSPw1omqHK8LPzDYpyk32aDnMIEyW9FPJF6IkX3Z6d2Dgseup3wD1/dJk9fDuJGr3uQCK0HC9uSjWeLIBFbTOZ9j8FIbdH0Xq2AqBeP3vwDtzMpoVEPqqNKGwVk1sabtjKoglDjWXfdqIqlDmdvK8oJL3KHEEaEy0gxbr1+6zrVq2Bj+ZUahvd8gHYmlkORDR0wN6NNPhfXmDnEGq8WU0efMIwjmHIg1mhUVYYGIsDMMgmwW+row+1sFOW+zmP3GtNKvPHyLEVVB3mWP5z8SeVve9MiIPm6JsihMfYnG0A93QNlzUsgdC78uqcA2SZ2jceOr6uxbuf6FeoHouMb0giiPl41YV6KpzNwdK0sH4ZarTGvquYrPSqDbrp67rEGJtTTyypzUoSeslMNCXzXS/aBphcB83M68bfSYk808hjRn+1UsdnXyL13LVm99NDv6z+imhJFH7IOXYfFAshqWKv2PiOjvUATn6cXuew==

  COMMON_TESTS_ARGS:
    go test -v github.com\jfrog\jfrog-cli --timeout 0 --rt.url="%JFROG_CLI_RT_URL%" --access.url="%JFROG_CLI_ACCESS_URL%" --rt.accessToken="%JFROG_CLI_ADMIN_TOKEN%"

  matrix:
  - VET:
    TEST_SUIT:
      go vet github.com\jfrog\jfrog-cli &&
      .\\build\\build.bat &&
      .\\jfrog.exe --version
  - ARTIFACTORY_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS%  --test.artifactory=true"
  - NPM_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.npm=true"
  - MAVEN_TESTS:
    TEST_SUIT:
     "%COMMON_TESTS_ARGS% --test.maven=true"
  - GRADLE_TESTS:
    TEST_SUIT:
      "choco install gradle -s %JFROG_CLI_RT_URL%/api/nuget/choco -u %JFROG_CLI_RT_USER% -p %JFROG_CLI_RT_PASSWORD% &&
      %COMMON_TESTS_ARGS% --test.gradle=true"
  - NUGET_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.nuget=true"
  - GO_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.go=true"
  - PIP_TESTS:
    TEST_SUIT:
      "C:\\Python37-x64\\python -m venv pip-venv &&
      %COMMON_TESTS_ARGS% --test.pip=true --rt.pipVirtualEnv=C:\\gopath\\src\\github.com\\jfrog\\jfrog-cli\\pip-venv\\Scripts"
  - DISTRIBUTION_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --rt.distUrl=%JFROG_CLI_DIST_URL% --rt.user=%JFROG_CLI_RT_USER% --test.distribution=true"
  - PLUGINS_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.plugins=true"

install:
  - ps: Install-Product node 15

test_script:
  - "%TEST_SUIT%"
