image:
  - Visual Studio 2017

build: off
stack: go 1.10, node 8, jdk 8
clone_folder: c:\gopath\src\github.com\jfrog\jfrog-cli-go
environment:
  GOPATH: c:\gopath
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GRADLE_OPTS: -Dorg.gradle.daemon=false

  JFROG_CLI_RT_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  JFROG_CLI_RT_USER:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  JFROG_CLI_RT_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==
  JFROG_CLI_BINTRAY_USER:
    secure: qr5vtfCwBPUAQyCqU2/0tQ==
  JFROG_CLI_BINTRAY_APIKEY:
    secure: 9KuCfPL8w7Pt0aBwO7leKNPjR8zhbKWp6DMGI6+4Ha8CuNMbizzk+O5c1R47V8LX

  COMMON_TESTS_ARGS:
    go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog --timeout 0 --test.maskCredentials --rt.url="%JFROG_CLI_RT_URL%" --rt.user="%JFROG_CLI_RT_USER%" --rt.password="%JFROG_CLI_RT_PASSWORD%"
  BT_CREDENTIALS_ARGS:
    --bt.user="%JFROG_CLI_BINTRAY_USER%" --bt.key="%JFROG_CLI_BINTRAY_APIKEY%"

  matrix:
  - VET:
    TEST_SUIT:
      go vet github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
  - ARTIFACTORY_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS%"
  - BINTRAY_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% %BT_CREDENTIALS_ARGS% --test.artifactory=false --test.bintray=true"
  - BUILD_TOOLS_TESTS:
    TEST_SUIT:
      "choco install gradle &&
      %COMMON_TESTS_ARGS% --test.artifactory=false --test.buildTools=true"
  - NUGET_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.artifactory=false --test.nuget=true"

test_script:
  - "%TEST_SUIT%"
