name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  insert-to-summary-file:
    runs-on: self-hosted
    steps:
#      Removed for self hosted, there is no need to setup go
#      - name: Setup Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: 1.20.x
#          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build current CLI
        run: go build .

      - name: Run CLI Ping
        run: ./jfrog-cli rt upload --spec=./testdata/filespecs/upload_dev_spec_b.json --dry-run --url="https://ecosysjfrog.jfrog.io/artifactory" --access-token=${{ secrets.PLATFORM_ADMIN_TOKEN }}
