name: pip Tests
on:
  push:
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [labeled]
jobs:
  pip-Tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    name: ${{ matrix.suite }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        suite: [pip]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
        if: ${{ matrix.suite == 'pip' }}

      - name: Setup Python virtual environment
        if: ${{ matrix.suite == 'pip' }}
        run: pip install virtualenv

      - name: Activate Python virtual env on Windows
        if: ${{ matrix.suite == 'pip' && runner.os == 'Windows' }}
        run: . venv\Scripts\activate.ps1

      - name: Activate Python virtual env on Posix
        if: ${{ matrix.suite == 'pip' && (runner.os == 'macOS' || runner.os == 'Linux') }}
        run: source venv/bin/activate

      - name: Run go vet
        run: go vet -v ./...

      - name: Run tests
        run: go test -v github.com/jfrog/jfrog-cli --timeout 0 --test.${{ matrix.suite }}=true --rt.url=${{ secrets.PLATFORM_URL }}artifactory --access.url=${{ secrets.PLATFORM_URL }}access --rt.distUrl=${{ secrets.PLATFORM_URL }}distribution --rt.user=${{ secrets.PLATFORM_USER }} --rt.accessToken=${{ secrets.PLATFORM_ADMIN_TOKEN }} --ci.runId=${{ runner.os }}-${{ matrix.suite }}
